### ISSUE TITLE
thread-view.html: classes do not correspond to their elements

### ISSUE THREAD

**Issue by glacambre** [astroidmail/astroid#654]
Sorry for spamming issues, I have a bit of free time and thought I'd toy with astroid a bit :)

I copied astroid's `thread-view.scss` file to my `~/.config/astroid/ui/thread-view.scss` directory and added the following two rules at the end, as described [here](https://github.com/astroidmail/astroid/wiki/Customizing-the-user-interface#thread-view-and-message-parts):
```css

.email_container .header_container * {
  display: none;
}

.email_container .header_container .tags {
  display: inline;
}
```
Surprisingly, this made everything disappear except for the subject (while I would have expected the tags to be the only remaining elements).

I didn't find a way to inspect the thread view's HTML in order to understand what was wrong, is there a way to do that?
